language: generic
branches:
  - master
  - gh-pages

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz
  - tar -xzvf hugo_0.55.6_Linux-64bit.tar.gz && mv hugo /tmp/

script:
  - git submodule add https://github.com/number317/aloha.git themes/aloha
  - /tmp/hugo 

after_script: 
  - cd ./public
  - git init
  - git config user.name "cheon"
  - git config user.email "cheon0112358d@gmail.com"
  - git add . 
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/number317/blog.git" master:gh-pages
