language: python
python:
  - "3.5.2"
branches:
  - master
  - gh-pages

install:
  - sudo apt-get --yes install snapd
  - sudo snap install hugo

script:
  - /snap/bin/hugo 

after_script: 
  - cd ./public
  - git init
  - git config user.name "cheon"
  - git config user.email "cheon0112358d@gmail.com"
  - git add . 
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/number317/blog.git" master:gh-pages
