baseURL = "https://www.cheon.site/blog/"
title = "cheon's blog"
theme = "simple"
author = "cheon"
canonifyurls = true
languagecode = "en"

[params]
  sitename = "cheon's blog"
  description = "Welcome to cheon's blog."
  disableWebFonts = false

[[menu.main]]
    name = "Home"
    url  = "https://www.cheon.site"
[[menu.main]]
    name = "Projects"
    url  = "https://github.com/number317"
